### ISSUE TITLE
Integrated Oxford English dictionary

### ISSUE THREAD

**Issue by kennedybaird** [wjdp/gotdict#39]
Hey there!

This work is all incredible, I want to thank you for it first!

I am wondering if you have thought of adding these definitions to the English dictionary so one doesn't have to change dictionaries when wanting a definition of a non ASOIAF-related term.

I am considering helping with this

**Comment by wjdp** [comment]
Thanks for the thanks, always nice to know people find this project useful :smile: 

I recognise that it's annoying that setting a dictionary on kindle devices means you miss out on definitions from other dictionaries. A solution to this would be nice but there are several issues:

- We cannot integrate OED defs as they're owned and copyrighted by Oxford Uni Press. We could use a free source such as [Wikimedia's Wiktionary](https://www.wiktionary.org/).
- Adding non-ASOIAF terms would inflate the dictionary hugely, this makes the index rather useless and makes management of the codebase a pain.

Suggestions open for a better way of doing this.

**Comment by wjdp** [comment]
**NB** Adding specific non-ASOIAF terms that are uncommon in modern usage is currently accepted, see http://gotdict.wjdp.uk/defs/dirk.html. If you find canidiates like these, please feel free to make an issue/submit a PR for.

*(There should be a document with guidelines for what should be in the project and in what style, but am yet to write it, see #7)*
