### ISSUE TITLE
Where's the .mobi file?

### ISSUE THREAD

**Issue by indiecognition** [wjdp/gotdict#41]
This is definitely a noobish request (not really a found issue): when I go to download the GOTDictionary, I only see links to source code. Where is the GOTDict.mobi file mentioned in the installation instructions?

Thanks!

**Comment by wjdp** [comment]
Looks like the latest release hasn't had the mobi file added to it (it's an automatic job done by our build system).

Use this one instead: http://gotdict.wjdp.uk/gotdict.mobi 😄 (Link from the project website)

**Comment by indiecognition** [comment]
Thank you!
