### ISSUE TITLE
definition for word "Magnar"

### ISSUE THREAD

**Issue by filipe-maia** [wjdp/gotdict#42]
The definition for the word "Magnar" doesn't exist. I found one in:
http://awoiaf.westeros.org/index.php/Magnar
Also, there are links in the dictionary incorrectly pointing to "House Magnar", when they should point to the definition of the word "Magnar", for example, in the definition of "Thenn" it should point to the definition of the word "Magnar", but it is pointing to "House Magnar").

Thanks for making this dictionary.

**Comment by wjdp** [comment]
Thanks for the reports @filipe-maia!
